services:
  db:
    image: postgres:17-alpine
    container_name: fuzzyrss-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuzzy_rss
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fuzzyrss-postgres-app
    ports:
      - "4000:4000"
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_URL: ecto://postgres:postgres@db:5432/fuzzy_rss
      SECRET_KEY_BASE: uYCtaRnHv8guzrfpWoLxGwnMj29yqhM/t3WENB3IRzgMNRnPFP/LumaChLVv2JIB
      PHX_HOST: localhost
      PORT: 4000
      DISABLE_MAGIC_LINK: true
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "/app/bin/migrate && /app/bin/server"

volumes:
  postgres_data:
